#kubectl apply -f pv-volume.yml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: job-tfjs-node-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/shared"